name: AI review

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
    review:
        runs-on: ubantu-latest

    permissions:
        contents: read
        pull-requests: write
